Scaffolding models from db, generic repository implemented, some sql procedures added
Dev-incubator/DIMS-Core.Double-2 pull request #2
Opened 2021-03-15 18:19 UTC by ArtyomKolosov2

2021-03-15 19:50 UTC, PushMeNow requested changes
Hi dude!
I did some comments. Let me know if any questions and get well faster! :)

2021-03-15 19:50 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Common/Helpers/RepositoriesExceptionHelper.cs
> +    public static class RepositoriesExceptionHelper
Hmm... Why repositories only? You can use this helper in other spaces.

2021-03-15 19:50 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSCoreContext.cs
> +                optionsBuilder.UseSqlServer("Data Source=(localdb)\\ProjectsV13;Initial Catalog=DIMS-Core.Database;Integrated Security=True;Pooling=False;Connect Timeout=30");
Could you remove it and use middleware?

2021-03-16 14:18 UTC, dbogdan2000 approved these changes

2021-03-17 19:04 UTC, PushMeNow approved these changes
Good! Approve

2021-03-17 19:06 UTC, merged